### ISSUE TITLE
<'NoneType' object has no attribute 'strip'> caused by some (rare) listings with empty 'city' attribute

### ISSUE THREAD

**Issue by aTnT** [JoeBashe/stl-scraper#8] opened 2023-01-22 11:01 UTC
Some (rare) listings seem to have an empty 'city' attribute, causing data collection to stop. This can be fixed by replacing at ./stl/endpoint/pdp.py", line 117, in __collect_listing_data:

From: 
`    'city':                   listing['city'].strip(),`

To:
`    'city':                   listing['city'],`

This will give anyway a more accurate description of the 'city' attribute.

Reproducible example:

```
(env) (base) jovyan@85c3ec4d10ec:~/work/Box2/Projects/stl-scraper$ ./stl.py search "Odemira, Portugal"
2023-01-22 09:50:42,092 [WARNING] Duplicate listing: 39365732
2023-01-22 09:51:03,001 [WARNING] Duplicate listing: 35678463
2023-01-22 09:51:26,439 [WARNING] Duplicate listing: 659751686113658473
2023-01-22 09:51:33,494 [WARNING] Duplicate listing: 43484879
2023-01-22 09:51:47,756 [WARNING] Duplicate listing: 27320398
2023-01-22 09:52:01,107 [WARNING] Duplicate listing: 689963964974757442
Traceback (most recent call last):
  File "/home/jovyan/work/Box2/Projects/stl-scraper/./stl.py", line 17, in <module>
    main()
  File "/home/jovyan/work/Box2/Projects/stl-scraper/./stl.py", line 10, in main
    StlCommand(arguments).execute()
  File "/home/jovyan/work/Box2/Projects/stl-scraper/stl/command/stl_command.py", line 73, in execute
    scraper.run(query, params)
  File "/home/jovyan/work/Box2/Projects/stl-scraper/stl/scraper/airbnb_scraper.py", line 46, in run
    listing_ids = self.__pdp.collect_listings_from_sections(data, data_cache)
  File "/home/jovyan/work/Box2/Projects/stl-scraper/stl/endpoint/pdp.py", line 99, in collect_listings_from_sections
    self.__collect_listing_data(listing_item, data_cache)
  File "/home/jovyan/work/Box2/Projects/stl-scraper/stl/endpoint/pdp.py", line 117, in __collect_listing_data
    'city':                   listing['city'].strip(),
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by JoeBashe** [comment] 2023-02-21 03:55
Hi @aTnT, thanks for the feedback!

I was able to reproduce this issue.

> This can be fixed by replacing at ./stl/endpoint/pdp.py", line 117, in __collect_listing_data:
> From:
>     'city':                   listing['city'].strip(),
> 
> To:
>     'city':                   listing['city'],
> 
> This will give anyway a more accurate description of the 'city' attribute.

I understand your thought process here, but the reason the `strip()` was added to city was because we were getting some cities with leading whitespace, which caused them to be recorded incorrectly. The `strip()` method removes the excess whitespace.

Instead, we can check to make sure the value is not `None` before calling `strip()`. That way the `city` will remain as `None`. E.g.:

```python
            'city':                   listing['city'].strip() if listing['city'] else None,
```


Then, later in the process (line 252 of `pdp.py`), the program will default to the searched city (stored in `geography`), if it sees the city is missing: 

```python
            'city':                   listing_data_cached.get('city', geography['city']),
```

**Comment by JoeBashe** [comment] 2023-02-27 05:12
@aTnT FYI I've heavily changed the way city names are handled, and added neighborhood names as well. The new code should still handle the case with no city, but that case should be much less frequent also. Closing the issue for now, feel free to reopen if you have any additional input. Thank you! :pray:

**Closed as completed by JoeBashe** 2023-02-27 05:12 UTC
